apiVersion: addon.open-cluster-management.io/v1alpha1
kind: AddOnTemplate
metadata:
  name: takebishi-device-gateway-3.3.0
spec:
  addonName: takebishi-device-gateway
  agentSpec:
    manifestConfigs:
      - resourceIdentifier:
          resource: persistentvolumeclaims
          name: takebishi-gateway
          namespace: takebishi
        updateStrategy:
          type: ServerSideApply
      - resourceIdentifier:
          resource: persistentvolumeclaims
          name: takebishi-sdcard
          namespace: takebishi
        updateStrategy:
          type: ServerSideApply
    workload:
      manifests:
      - kind: Namespace
        apiVersion: v1
        metadata:
          labels:
            pod-security.kubernetes.io/audit: privileged
            pod-security.kubernetes.io/enforce: privileged
            pod-security.kubernetes.io/warn: privileged
            security.openshift.io/scc.podSecurityLabelSync: "false"
          name: takebishi
      - kind: PersistentVolumeClaim
        apiVersion: v1
        metadata:
          name: takebishi-gateway
          namespace: takebishi
        spec:
          storageClassName: "{{STORAGE_CLASS_NAME}}"
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
      - kind: PersistentVolumeClaim
        apiVersion: v1
        metadata:
          name: takebishi-sdcard
          namespace: takebishi
        spec:
          storageClassName: "{{STORAGE_CLASS_NAME}}"
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
      - kind: ConfigMap
        apiVersion: v1
        metadata:
          name: dgw-settings
          namespace: takebishi
        data:
          setting.dxg: |
            {"CommInterface":{"Mqtt":[{"name":"amq-mqtt","setting":[{"name":"serverAddress","value":"mqtt.amq-broker.svc"},{"name":"clientId","value":"takebishi-dgw"}]}]},"System":{"Config":{"setting":[{"name":"autoStart","value":"true"},{"name":"language","value":"1"}]},"TimeConfig":{"setting":[{"name":"timeZone","value":"Etc/UTC"},{"name":"useNtpSyncronous","value":"false"},{"name":"useSleMode","value":"true"},{"name":"useUpdateHardwareClock","value":"true"},{"name":"updateHWClockExecTime","value":"1"}]},"User":{"users":[{"name":"administrator","setting":[{"name":"useWebUI","value":"true"},{"name":"password","value":"admin"}]}]},"firewall":[{"name":"CONST_FIREWALL","setting":[{"name":"validFlag","value":"true"},{"name":"type","value":"WEB User Interface"},{"name":"inputport","value":"0"},{"name":"sourceAddress","value":"0.0.0.0"},{"name":"sourceAddressMask","value":"0"}]},{"name":"DEFAULT_FIREWALL","setting":[{"name":"validFlag","value":"true"},{"name":"type","value":"All Service"},{"name":"inputport","value":"99"},{"name":"sourceAddress","value":"0.0.0.0"},{"name":"sourceAddressMask","value":"0"}]}]}}
      - kind: ServiceAccount
        apiVersion: v1
        metadata:
          name: takebishi
          namespace: takebishi
      - kind: RoleBinding
        apiVersion: rbac.authorization.k8s.io/v1
        metadata:
          name: system:openshift:scc:privileged
          namespace: takebishi
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: ClusterRole
          name: system:openshift:scc:privileged
        subjects:
        - kind: ServiceAccount
          name: takebishi
          namespace: takebishi
      - kind: Route
        apiVersion: route.openshift.io/v1
        metadata:
          name: dgw
          namespace: takebishi
        spec:
          to:
            kind: Service
            name: dgw
            weight: 100
          port:
            targetPort: http
          wildcardPolicy: None
      - kind: Service
        apiVersion: v1
        metadata:
          name: dgw
          namespace: takebishi
        spec:
          type: ClusterIP
          ports:
            - name: http
              protocol: TCP
              port: 80
              targetPort: 80
            - name: https
              protocol: TCP
              port: 443
              targetPort: 443
          selector:
            app: takebishi-dgw
      - kind: Deployment
        apiVersion: apps/v1
        metadata:
          name: takebishi-dgw
          namespace: takebishi
        spec:
          selector:
            matchLabels:
              app: takebishi-dgw
          replicas: 1
          template:
            metadata:
              labels:
                app: takebishi-dgw
            spec:
              containers:
                - name: takebishi-dgw
                  image: quay.io/yono/dgw:latest
                  imagePullPolicy: IfNotPresent
                  ports:
                    - containerPort: 80
                      protocol: TCP
                    - containerPort: 443
                      protocol: TCP
                  volumeMounts:
                  - mountPath: /etc/dxpgateway
                    name: pvc-takebishi-gateway
                  - mountPath: /mnt/sdcard
                    name: pvc-takebishi-sdcard
                  - mountPath: /etc/dxpgateway/config/setting.dxg
                    name: dgw-setting
                    subPath: setting.dxg
                  securityContext:
                    privileged: true
              volumes:
                - name: pvc-takebishi-gateway
                  persistentVolumeClaim:
                    claimName: takebishi-gateway
                - name: pvc-takebishi-sdcard
                  persistentVolumeClaim:
                    claimName: takebishi-sdcard
                - name: dgw-setting
                  configMap:
                    name: dgw-settings
                    items:
                      - key: setting.dxg
                        path: setting.dxg
              serviceAccount: takebishi
              serviceAccountName: takebishi
