kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: amq-broker
  namespace: amq-broker
spec:
  storageClassName: "{{STORAGE_CLASS_NAME}}"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi