{
 "title": "Kepler (Operator) Exporter Dashboard",
 "description": "Dashboard (Operator) for Kepler Exporter",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(acm_managed_cluster_labels{openshiftVersion_major!=\"3\"},name)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kepler_container_package_joules_total{cluster=\"$cluster\"},container_namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kepler_container_package_joules_total{cluster=\"$cluster\",container_namespace=\"$namespace\"},pod_name)"
    }
   },
   { "name": "watt_per_second_to_kWh", "query": "0.000000277777777777778" }
  ]
 },
 "panels": [
  {
   "title": "Power Consumption Overview ($cluster)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "CPU Architecture by Nodes",
   "type": "table",
   "description": "CPU architecture determined by Kepler",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count by (cpu_architecture)(kepler_node_info{cluster=\"$cluster\"})",
     "legendFormat": "{{cpu_architecture}}"
    }
   ]
  },
  {
   "title": "Total Energy Consumption (kWh) - Last 24 hours",
   "type": "stat",
   "description": "Total Energy Consumption (kWh) - Last 24 hours",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(kepler_container_joules_total{cluster=\"$cluster\"}[24h:1m])) * $watt_per_second_to_kWh"
    }
   ]
  },
  {
   "title": "Top 10 Energy Consuming Namespaces (kWh) in Last 24 hours",
   "type": "bargauge",
   "description": "Total Power Consumption for Top 10 Namespaces (kWh per day)",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (container_namespace) (increase(kepler_container_joules_total{cluster=\"$cluster\"}[24h:1m]))) * $watt_per_second_to_kWh",
     "legendFormat": "{{container_namespace}}"
    }
   ]
  },
  { "title": "Power Consumption ($cluster)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Total Power Consumption (W) in $namespace",
   "type": "timeseries",
   "description": "Total Power Consumption (W) in Namespace",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum(sum by (container_namespace, pod_name) (irate(kepler_container_package_joules_total{cluster=\"$cluster\",container_namespace=~\"$namespace\"}[10m])))",
     "legendFormat": "PKG"
    },
    {
     "expr": "sum(sum by (container_namespace, pod_name) (irate(kepler_container_dram_joules_total{cluster=\"$cluster\",container_namespace=~\"$namespace\"}[10m])))",
     "legendFormat": "DRAM"
    },
    {
     "expr": "sum(sum by (container_namespace, pod_name) (irate(kepler_container_other_joules_total{cluster=\"$cluster\",container_namespace=~\"$namespace\"}[10m])))",
     "legendFormat": "OTHER"
    },
    {
     "expr": "sum(sum by (container_namespace, pod_name) (irate(kepler_container_gpu_joules_total{cluster=\"$cluster\",container_namespace=~\"$namespace\"}[10m])))",
     "legendFormat": " GPU"
    }
   ]
  },
  {
   "title": "Total Energy Consumption in $namespace (kWh) - Last 1 hour",
   "type": "timeseries",
   "description": "Total Energy Consumption in Namespace (kWh) - Last 1 hour",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "sum by (container_namespace) (increase(kepler_container_package_joules_total{cluster=\"$cluster\",container_namespace=~\"$namespace\"}[1h:15s])) * $watt_per_second_to_kWh",
     "legendFormat": "PKG (CORE + UNCORE)"
    },
    {
     "expr": "sum by (container_namespace) (increase(kepler_container_dram_joules_total{cluster=\"$cluster\",container_namespace=~\"$namespace\"}[1h:15s])) * $watt_per_second_to_kWh",
     "legendFormat": "DRAM"
    },
    {
     "expr": "sum by (container_namespace) (increase(kepler_container_other_joules_total{cluster=\"$cluster\",container_namespace=~\"$namespace\"}[1h:15s])) * $watt_per_second_to_kWh",
     "legendFormat": "OTHER"
    },
    {
     "expr": "sum by (container_namespace) (increase(kepler_container_gpu_joules_total{cluster=\"$cluster\",container_namespace=~\"$namespace\"}[1h:15s])) * $watt_per_second_to_kWh",
     "legendFormat": " GPU"
    }
   ]
  },
  {
   "title": "PKG Power Consumption (W) by Pods in $namespace",
   "type": "timeseries",
   "description": "The total energy spent in PKG by a container.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum by (container_namespace, pod_name) (irate(kepler_container_package_joules_total{cluster=\"$cluster\",container_namespace=~\"$namespace\", pod_name=~\"$pod\"}[10m]))",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "DRAM Power Consumption (W) by Pods in $namespace",
   "type": "timeseries",
   "description": "The total energy spent in DRAM by a container.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum by (container_namespace, pod_name) (irate(kepler_container_dram_joules_total{cluster=\"$cluster\",container_namespace=~\"$namespace\", pod_name=~\"$pod\"}[10m]))",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "OTHER Power Consumption (W) by Pods in $namespace",
   "type": "timeseries",
   "description": "The total energy spent in OTHER by a container.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum by (pod_name) (kepler:other_joules_watts:1m:by_ns_pod{container_namespace=~\"$namespace\", pod_name=~\"$pod\"})",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "GPU Power Consumption (W) by Pods in $namespace",
   "type": "timeseries",
   "description": "The total energy spent in GPU by a container.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum by (pod_name) (sum by (container_namespace, pod_name) (irate(kepler_container_gpu_joules_total{cluster=\"$cluster\",container_namespace=~\"$namespace\",pod_name=~\"$pod\"}[10m])))",
     "legendFormat": "{{pod_name}}"
    }
   ]
  }
 ]
}