kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: takebishi-sdcard
  namespace: takebishi
spec:
  storageClassName: "{{STORAGE_CLASS_NAME}}"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
