kind: Service
apiVersion: v1
metadata:
  name: dgw
  namespace: takebishi
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  selector:
    app: takebishi-dgw
