kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: takebishi-gateway
  namespace: takebishi
spec:
  storageClassName: "{{STORAGE_CLASS_NAME}}"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  volumeName: takebishi-demo-pv-3
